[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/"
  to = "/home/home.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about/about.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200